version: 2.1

jobs:
  test:
    executor: xcode-11
    steps:
      - checkout
      - xcodebuild test -project Tests/ViewStateTests.xcodeproj -scheme ViewStateTests
      - xcodebuild build -project Example/ViewStateExample.xcodeproj -scheme ViewStateExample

executors:
  xcode-11:
    macos:
      xcode: "11.4.0"
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    shell: /bin/bash --login -eo pipefail

workflows:
  version: 2
  integration:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
